### PR TITLE
Darwin Core mapping

### PR DESCRIPTION
**Pull request by LienReyserhove**
This PR includes a detailed description of how the following Darwin Core files are generated:
1. `taxon.csv`
2. `vernacular_names.csv`
3. `distribution.csv`
4. `description.csv`

These files are generated using several .Rmd files:
1. `1_pre_processing.Rmd`
2. `2_dwc_taxon_mapping.Rmd`
3. `3_dwc_vernacularname_mapping.Rmd`
4. `4_dwc_distribution_mapping.Rmd`
5. `5_dwc_description_mapping.Rmd`

This is an overview of all Darwin Core terms in the files + a reference to the .Rmd files needed to generate these files.

## Taxon core

Remarks:
- Cleaning of the taxonomic information is outside of the scope of the mapping. Some issues on this topic:
  - https://github.com/trias-project/daisie-checklist/issues/17
  - https://github.com/trias-project/daisie-checklist/issues/24
- taxonRank information should be verified/corrected as it is based on, sometimes dubious, scientific names, see #17 
- References are integrated under `taxonRemarks`

- [x] language
- [x] license
- [x] rightsHolder
- [x] datasetID
- [x] institutionCode
- [x] datasetName
- [x] taxonID
- [x] scientificName
- [x] kingdom
- [x] phylum
- [x] class
- [x] order
- [x] family
- [x] genus
- [x] specificEpithet
- [x] infraspecificEpithet
- [x] taxonRank
- [x] taxonRemarks

## Vernacular names

- [x] taxonID
- [x] vernacularName
- [x] source
- [x] language

## Distribution

- [x] taxonID
- [x] locationID (see #12 and #13)
- [x] locality
- [x] countryCode
- [x] occurrenceStatus
- [x] establishmentMeans
- [x] eventDate
- [ ] source (see #22)
- [x] occurrenceRemarks

## Description

- [x] Habitat
  - [x] taxonID
  - [x] description
  - [x] type
  - [x] source
- [x] Native range
  - [x] taxonID
  - [x] description
  - [x] type
  - [x] source
- [x] Ecofunctional group
  - [x] taxonID
  - [x] description
  - [x] type
  - [x] source

### CODE REVIEW

**Review by peterdesmet — CHANGES_REQUESTED** [review]
- [x] All files: `taxonID` seem to be sorted alphabetically rather than numerically.
- [x] All files: use `here::here()`
- [x] Cleanup `interim` data is not required

## taxon

- [x] license: use `http://creativecommons.org/licenses/by/4.0/`
- [x] rightsHolder/institutionCode: CEH is short, but does not google well
- [x] datasetName: DAISIE stands for `Delivering Alien Invasive Species Inventories for Europe (DAISIE)`, so I'm wondering why name doesn't more closely resemble that, especially the word "invasive" **was discussed with David, but changed it now to "The DAISIE inventory of alien invasive species in Europe"**  : Suggest to use `DAISIE - Inventory of alien invasive species in Europe`
- [x] taxonID: are the short ids on purpose? **yes, is the identifier of the taxon in the DAISIE database**
- [x] scientificName: authorship mostly appears in quotes, why? `Abudefduf vaigiensis "(Quoy & Gaimard, 1825)"` **This is integrated as such in the database and cleaning of all author information is outside of the scope of the mapping** Would just remove `"`
- [x] higher classification and taxonRank: did not review in depth in light of #17
- [x] taxonRemarks: this field is not included: **now added, is a reference to the source**

## distribution

- [x] locationID: would not have space in `TDWG: BLR`, `DAISIE: GRC-II`. Also, what standard is this referring to? https://www.tdwg.org/standards/wgsrpd/ ? **Use `WGSRPD:CODE` and concatenate with `space|space`**
- [x] locationID: some codes and localities are concatenated: `TDWG:TUR|DIHO23_4:MP3.3`. Why not create two records? **they are related: e.g. coast for country**
- [x] countryCode: odd values are 31, Åland, FRR, GRC-OO and empty
- [x] occurrenceStatus: empty for 16K records **like this in source db**
- [x] establishmentMeans: empty for 1.9K records **like this in source db**
- [x] eventDate: contains non-iso dates: `01-04-1993/31-03-2006`
- [x] occurrenceRemarks: sometimes ends with `;`, e.g. `region_of_first_record: Gat van Ouwerkerk near the Oosterschelde estuary;`
- [x] occurrenceRemarks: why is this field included if it is also in description? @peterdesmet to check

## description

- [x] `current distribution`: Odd unknown values `TDWG: BLT-ES - UnknownUnknown` **Would move this to occurrenceRemarks** @peterdesmet to check
- [x] It is unclexr what the codes stand for before the actual value: `TDWG:EGY|IHO23_4:M3.1 - Red Sea` **I would argue NOT to map this field** @peterdesmet to check
- [x] Would make values for `ecofunctional group` lowercase **leave as is**
- [x] Write code after value: Write as `Pelagic water column (A7 level 2)`
- [x] Question marks in eunis habitats, e.g. `I?`
- [x] degree of establishment: unclear what code is in values `TDWG:ISR|IHO23_4:M3.1 - Established` @peterdesmet to check
- [x] Normally we also add a language field **not certain it is all English**
- [x] Cleanup descriptions now mapped in `occurrenceRemarks`

## vernacular names

- [x] Would name file `vernacularname.csv` cf. other datasets

**Comment by LienReyserhove** [comment]
Integrated the requested changes, ready for review

**Review by peterdesmet — APPROVED** [review]

**Comment by peterdesmet** [comment]
Nice work! 👏

**Comment by peterdesmet** [comment]
Important: see #31

**Pull request merged**
